In [5]:
import os
import re
import numpy as np
import pandas as pd
from tqdm.auto import tqdm

import statsmodels.formula.api as smf

import warnings

os.chdir('../../..')

warnings.filterwarnings("ignore")

# --- helpers ---

def load_band_table(path: str) -> pd.DataFrame:
    df = pd.read_csv(path)

    # numeric ids
    for c in ("s_id", "t_id", "age", "label", "stim_label"):
        if c in df.columns:
            df[c] = pd.to_numeric(df[c], errors="coerce")

    # string-like
    for c in ("gender", "handiness", "day_time", "stim_type", "task_type"):
        if c in df.columns:
            df[c] = df[c].astype("string")

    return df


def infer_feature_cols(df: pd.DataFrame):
    """Возвращает список колонок вида ch{N}_{Band}"""
    cols = []
    for c in df.columns:
        if isinstance(c, str) and re.match(r"^ch\d+_.+$", c):
            cols.append(c)
    return cols


def parse_ch_band(col: str):
    m = re.match(r"^ch(\d+)_(.+)$", col)
    if not m:
        return None, None
    return int(m.group(1)), m.group(2)


def map_to_group_series(df: pd.DataFrame, feature_name: str) -> pd.Series:
    """
    Превращает сырые значения фичи в групповые метки из FEATURE_GROUPS[feature].
    Возвращает Series с метками групп (строки) или <NA>.
    """
    groups = FEATURE_GROUPS[feature_name]  # {group_label: [allowed_values...]}

    # где брать исходное значение
    src_col = feature_name
    if src_col not in df.columns:
        # совместимость: иногда stim_label лежит в label
        if feature_name == "stim_label" and "label" in df.columns:
            src_col = "label"
        else:
            raise KeyError(f"Нет колонки '{feature_name}' в band_table")

    s = df[src_col]

    out = pd.Series(pd.NA, index=df.index, dtype="string")

    for g_label, allowed in groups.items():
        allowed_set = set(allowed)

        if feature_name in ("age", "stim_label"):
            # числовые
            mask = s.isin(list(allowed_set))
        else:
            # строковые
            mask = s.astype("string").isin([str(x) for x in allowed_set])

        out.loc[mask] = str(g_label)

    return out

In [7]:
def run_interaction_for_pair(
    band_table_path: str,
    feature_A: str,
    feature_B: str,
    alpha: float = 0.05,
    min_subjects: int = 8,
    save_dir: str = "./Supplementary",
):
    df = load_band_table(band_table_path)

    # только строки с валидным s_id
    df = df[df["s_id"].notna()].copy()

    # маппинг в групповые метки (по FEATURE_GROUPS)
    A = map_to_group_series(df, feature_A)
    B = map_to_group_series(df, feature_B)

    df["_A"] = A
    df["_B"] = B

    # выбрасываем строки не попавшие в группы
    df = df[df["_A"].notna() & df["_B"].notna()].copy()

    # минимум по числу людей
    n_subj = df["s_id"].nunique()
    if n_subj < min_subjects:
        raise RuntimeError(f"Слишком мало субъектов для модели: {n_subj} < {min_subjects}")

    feat_cols = infer_feature_cols(df)
    rows = []

    pbar = tqdm(feat_cols, desc=f"Interaction: {feature_A}×{feature_B}", unit="feat", dynamic_ncols=True)
    for col in pbar:
        ch, band = parse_ch_band(col)
        if ch is None:
            continue

        d = df[["s_id", "_A", "_B", col]].copy()
        d[col] = pd.to_numeric(d[col], errors="coerce")
        d = d[d[col].notna()].copy()
        if d.empty:
            continue

        # требования к уникальным уровням
        if d["_A"].nunique() < 2 or d["_B"].nunique() < 2:
            continue

        # минимум субъектов в данных именно этого признака
        if d["s_id"].nunique() < min_subjects:
            continue

        try:
            # full model
            model = smf.ols(f"{col} ~ C(_A) * C(_B)", data=d)
            res = model.fit(cov_type="cluster", cov_kwds={"groups": d["s_id"]})
        except Exception:
            continue

        # выбираем параметры interaction
        param_names = list(res.params.index)
        inter_idx = [
            i for i, name in enumerate(param_names)
            if (":" in name) and ("C(_A)" in name) and ("C(_B)" in name)
        ]
        if not inter_idx:
            continue

        # joint Wald test: все interaction = 0
        R = np.zeros((len(inter_idx), len(param_names)), dtype=float)
        for r, j in enumerate(inter_idx):
            R[r, j] = 1.0

        try:
            wt = res.wald_test(R)  # robust cov already inside res
            p_int = float(wt.pvalue)
            stat = float(np.asarray(wt.statistic).reshape(-1)[0])
            df_int = int(getattr(wt, "df_denom", getattr(wt, "df_num", len(inter_idx))))
        except Exception:
            p_int = np.nan
            stat = np.nan
            df_int = len(inter_idx)

        # удобно: коэффициент interaction (если 2x2, он один)
        if len(inter_idx) == 1:
            inter_name = param_names[inter_idx[0]]
            inter_coef = float(res.params.iloc[inter_idx[0]])
            inter_p = float(res.pvalues.iloc[inter_idx[0]])
        else:
            inter_name = "MULTI"
            inter_coef = np.nan
            inter_p = np.nan

        rows.append({
            "feature_A": feature_A,
            "feature_B": feature_B,
            "channel": ch,
            "band": band,
            "n_obs": int(len(d)),
            "n_subjects": int(d["s_id"].nunique()),
            "levels_A": int(d["_A"].nunique()),
            "levels_B": int(d["_B"].nunique()),
            "p_interaction_joint": p_int,
            "stat_interaction_joint": stat,
            "df_interaction_terms": len(inter_idx),
            "interaction_term": inter_name,
            "interaction_coef": inter_coef,
            "interaction_p_single": inter_p,  # только если 2x2
        })

        pbar.set_postfix({"p_int": f"{p_int:.3g}" if np.isfinite(p_int) else "nan"})

    out = pd.DataFrame(rows)
    if not out.empty:
        out = out.sort_values(["p_interaction_joint", "n_subjects"], ascending=[True, False]).reset_index(drop=True)

    # save
    os.makedirs(save_dir, exist_ok=True)
    safeA = feature_A.replace("/", "-")
    safeB = feature_B.replace("/", "-")
    out_path = os.path.join(save_dir, f"interaction__{safeA}x{safeB}.csv")
    out.to_csv(out_path, index=False)

    return out

In [10]:
band_table_path = "./Supplementary/Analysis/band_table.csv"

pairs = [
    ("day_time", "gender"),
    ("stim_type", "gender"),
    ("stim_label", "gender"),
    ("day_time", "age"),
    ("day_time", "handiness"),
    ("age", "handiness"),
]
FEATURE_GROUPS = {
    "day_time": {
        "Day": ["Day"],
        "Evening": ["Evening"],
    },
    "stim_type": {
        "r": ["r"],
        "g": ["g"],
    },
    "stim_label": {
        "line":   [0, 1, 4, 6, 7, 11, 8],
        "figure": [2, 3, 5, 9, 10, 12],
    },
    "gender": {
        "m": ["m"],
        "f": ["f"],
    },
    "age": {
        "18-22": [18, 19, 20, 21, 22],
        "23-29": [23, 24, 25, 25, 26, 27, 28, 29],
        "30-35": [30, 31, 32, 33, 34, 35],
    },
    "handiness": {
        "l": ["l"],
        "r": ["r"],
    },
}
interaction_results = {}
for a, b in pairs:
    df_int = run_interaction_for_pair(
        band_table_path=band_table_path,
        feature_A=a,
        feature_B=b,
        alpha=0.05,
        min_subjects=8,
        save_dir="Data/EEG-Visual-Experiment/Supplementary/Analysis",
    )
    interaction_results[(a, b)] = df_int
    print(f"\nTOP interaction: {a} × {b}")
    display(df_int.head(15))

Interaction: day_time×gender:   0%|          | 0/252 [00:00<?, ?feat/s]

TOP interaction: day_time × gender

,feature_A,feature_B,channel,band,n_obs,n_subjects,levels_A,levels_B,p_interaction_joint,stat_interaction_joint,df_interaction_terms,interaction_term,interaction_coef,interaction_p_single
0,day_time,gender,28,Beta,945,24,2,2,0.000021,18.122474,1,C(_A)[T.Evening]:C(_B)[T.m],0.095280,0.000021
1,day_time,gender,6,Beta,945,24,2,2,0.004971,7.890119,1,C(_A)[T.Evening]:C(_B)[T.m],0.034150,0.004971
2,day_time,gender,33,Beta,945,24,2,2,0.006831,7.316954,1,C(_A)[T.Evening]:C(_B)[T.m],0.074790,0.006831
3,day_time,gender,31,Beta,945,24,2,2,0.007185,7.226123,1,C(_A)[T.Evening]:C(_B)[T.m],0.289561,0.007185
4,day_time,gender,23,Beta,945,24,2,2,0.008290,6.969776,1,C(_A)[T.Evening]:C(_B)[T.m],0.037626,0.008290
5,day_time,gender,32,Beta,945,24,2,2,0.022981,5.169963,1,C(_A)[T.Evening]:C(_B)[T.m],0.169431,0.022981
6,day_time,gender,21,Beta,945,24,2,2,0.026856,4.900073,1,C(_A)[T.Evening]:C(_B)[T.m],0.025916,0.026856
7,day_time,gender,60,Beta,945,24,2,2,0.031369,4.632630,1,C(_A)[T.Evening]:C(_B)[T.m],0.144568,0.031369
8,day_time,gender,12,Tetta,945,24,2,2,0.037335,4.335069,1,C(_A)[T.Evening]:C(_B)[T.m],-0.112482,0.037335
9,day_time,gender,5,Beta,945,24,2,2,0.040900,4.180164,1,C(_A)[T.Evening]:C(_B)[T.m],0.054953,0.040900
10,day_time,gender,58,Beta,945,24,2,2,0.049786,3.848646,1,C(_A)[T.Evening]:C(_B)[T.m],0.107227,0.049786
11,day_time,gender,38,Beta,945,24,2,2,0.054950,3.683592,1,C(_A)[T.Evening]:C(_B)[T.m],0.010553,0.054950
12,day_time,gender,12,Alpha,945,24,2,2,0.057143,3.618428,1,C(_A)[T.Evening]:C(_B)[T.m],-0.162144,0.057143
13,day_time,gender,10,Beta,945,24,2,2,0.063219,3.450868,1,C(_A)[T.Evening]:C(_B)[T.m],0.042869,0.063219
14,day_time,gender,11,Tetta,945,24,2,2,0.067787,3.335800,1,C(_A)[T.Evening]:C(_B)[T.m],-0.064879,0.067787

Interaction: stim_type×gender:   0%|          | 0/252 [00:00<?, ?feat/s]

TOP interaction: stim_type × gender

,feature_A,feature_B,channel,band,n_obs,n_subjects,levels_A,levels_B,p_interaction_joint,stat_interaction_joint,df_interaction_terms,interaction_term,interaction_coef,interaction_p_single
0,stim_type,gender,8,Delta,1218,32,2,2,0.012671,6.214527,1,C(_A)[T.r]:C(_B)[T.m],0.195337,0.012671
1,stim_type,gender,59,Beta,1218,32,2,2,0.022952,5.172107,1,C(_A)[T.r]:C(_B)[T.m],-0.155965,0.022952
2,stim_type,gender,46,Alpha,1218,32,2,2,0.037449,4.329875,1,C(_A)[T.r]:C(_B)[T.m],-0.030176,0.037449
3,stim_type,gender,8,Tetta,1218,32,2,2,0.044602,4.033621,1,C(_A)[T.r]:C(_B)[T.m],0.106115,0.044602
4,stim_type,gender,40,Delta,1218,32,2,2,0.049347,3.863502,1,C(_A)[T.r]:C(_B)[T.m],0.131802,0.049347
5,stim_type,gender,46,Beta,1218,32,2,2,0.056053,3.650471,1,C(_A)[T.r]:C(_B)[T.m],-0.009130,0.056053
6,stim_type,gender,2,Delta,1218,32,2,2,0.064935,3.406633,1,C(_A)[T.r]:C(_B)[T.m],0.145347,0.064935
7,stim_type,gender,5,Delta,1218,32,2,2,0.066787,3.360283,1,C(_A)[T.r]:C(_B)[T.m],0.166837,0.066787
8,stim_type,gender,8,Alpha,1218,32,2,2,0.067951,3.331834,1,C(_A)[T.r]:C(_B)[T.m],0.095370,0.067951
9,stim_type,gender,49,Beta,1218,32,2,2,0.078729,3.090941,1,C(_A)[T.r]:C(_B)[T.m],-0.008896,0.078729
10,stim_type,gender,58,Tetta,1218,32,2,2,0.081790,3.028960,1,C(_A)[T.r]:C(_B)[T.m],0.055979,0.081790
11,stim_type,gender,57,Tetta,1218,32,2,2,0.085862,2.950290,1,C(_A)[T.r]:C(_B)[T.m],0.069764,0.085862
12,stim_type,gender,57,Delta,1218,32,2,2,0.092272,2.834278,1,C(_A)[T.r]:C(_B)[T.m],0.301042,0.092272
13,stim_type,gender,8,Beta,1218,32,2,2,0.093424,2.814360,1,C(_A)[T.r]:C(_B)[T.m],0.080240,0.093424
14,stim_type,gender,43,Tetta,1218,32,2,2,0.093650,2.810486,1,C(_A)[T.r]:C(_B)[T.m],0.011780,0.093650

Interaction: stim_label×gender:   0%|          | 0/252 [00:00<?, ?feat/s]

TOP interaction: stim_label × gender

,feature_A,feature_B,channel,band,n_obs,n_subjects,levels_A,levels_B,p_interaction_joint,stat_interaction_joint,df_interaction_terms,interaction_term,interaction_coef,interaction_p_single
0,stim_label,gender,51,Alpha,812,32,2,2,0.013708,6.075354,1,C(_A)[T.line]:C(_B)[T.m],-0.073728,0.013708
1,stim_label,gender,51,Tetta,812,32,2,2,0.026146,4.946362,1,C(_A)[T.line]:C(_B)[T.m],-0.084490,0.026146
2,stim_label,gender,51,Beta,812,32,2,2,0.055535,3.665946,1,C(_A)[T.line]:C(_B)[T.m],-0.058967,0.055535
3,stim_label,gender,48,Beta,812,32,2,2,0.065349,3.396137,1,C(_A)[T.line]:C(_B)[T.m],0.013111,0.065349
4,stim_label,gender,34,Beta,812,32,2,2,0.068053,3.329362,1,C(_A)[T.line]:C(_B)[T.m],0.013885,0.068053
5,stim_label,gender,40,Beta,812,32,2,2,0.073874,3.194782,1,C(_A)[T.line]:C(_B)[T.m],0.073154,0.073874
6,stim_label,gender,50,Tetta,812,32,2,2,0.086306,2.941957,1,C(_A)[T.line]:C(_B)[T.m],-0.063561,0.086306
7,stim_label,gender,40,Alpha,812,32,2,2,0.087876,2.912849,1,C(_A)[T.line]:C(_B)[T.m],0.046804,0.087876
8,stim_label,gender,19,Beta,812,32,2,2,0.101510,2.681659,1,C(_A)[T.line]:C(_B)[T.m],0.045463,0.101510
9,stim_label,gender,40,Tetta,812,32,2,2,0.104682,2.632723,1,C(_A)[T.line]:C(_B)[T.m],0.055479,0.104682
10,stim_label,gender,43,Beta,812,32,2,2,0.110783,2.543023,1,C(_A)[T.line]:C(_B)[T.m],0.018846,0.110783
11,stim_label,gender,15,Beta,812,32,2,2,0.135309,2.230514,1,C(_A)[T.line]:C(_B)[T.m],0.078519,0.135309
12,stim_label,gender,44,Beta,812,32,2,2,0.141186,2.164990,1,C(_A)[T.line]:C(_B)[T.m],0.027678,0.141186
13,stim_label,gender,9,Alpha,812,32,2,2,0.143058,2.144752,1,C(_A)[T.line]:C(_B)[T.m],0.082711,0.143058
14,stim_label,gender,7,Beta,812,32,2,2,0.149722,2.075079,1,C(_A)[T.line]:C(_B)[T.m],0.004984,0.149722

Interaction: day_time×age:   0%|          | 0/252 [00:00<?, ?feat/s]

TOP interaction: day_time × age

,feature_A,feature_B,channel,band,n_obs,n_subjects,levels_A,levels_B,p_interaction_joint,stat_interaction_joint,df_interaction_terms,interaction_term,interaction_coef,interaction_p_single
0,day_time,age,54,Beta,966,25,2,3,0.000036,17.053049,2,MULTI,NaN,NaN
1,day_time,age,28,Delta,966,25,2,3,0.000517,12.054254,2,MULTI,NaN,NaN
2,day_time,age,48,Beta,966,25,2,3,0.000736,11.395250,2,MULTI,NaN,NaN
3,day_time,age,21,Beta,966,25,2,3,0.001455,10.135310,2,MULTI,NaN,NaN
4,day_time,age,45,Delta,966,25,2,3,0.001566,9.999563,2,MULTI,NaN,NaN
5,day_time,age,27,Beta,966,25,2,3,0.001847,9.695305,2,MULTI,NaN,NaN
6,day_time,age,48,Delta,966,25,2,3,0.003023,8.793793,2,MULTI,NaN,NaN
7,day_time,age,36,Tetta,966,25,2,3,0.003033,8.787525,2,MULTI,NaN,NaN
8,day_time,age,49,Beta,966,25,2,3,0.003383,8.588269,2,MULTI,NaN,NaN
9,day_time,age,44,Delta,966,25,2,3,0.004252,8.172827,2,MULTI,NaN,NaN
10,day_time,age,46,Delta,966,25,2,3,0.005357,7.754664,2,MULTI,NaN,NaN
11,day_time,age,49,Tetta,966,25,2,3,0.005999,7.550685,2,MULTI,NaN,NaN
12,day_time,age,24,Alpha,966,25,2,3,0.006534,7.396707,2,MULTI,NaN,NaN
13,day_time,age,47,Delta,966,25,2,3,0.006998,7.273549,2,MULTI,NaN,NaN
14,day_time,age,35,Delta,966,25,2,3,0.007160,7.232458,2,MULTI,NaN,NaN

Interaction: day_time×handiness:   0%|          | 0/252 [00:00<?, ?feat/s]

TOP interaction: day_time × handiness

,feature_A,feature_B,channel,band,n_obs,n_subjects,levels_A,levels_B,p_interaction_joint,stat_interaction_joint,df_interaction_terms,interaction_term,interaction_coef,interaction_p_single
0,day_time,handiness,8,Tetta,924,24,2,2,3.025316e-131,594.221078,1,C(_A)[T.Evening]:C(_B)[T.r],-0.889194,3.025316e-131
1,day_time,handiness,12,Beta,924,24,2,2,4.695550e-119,538.178549,1,C(_A)[T.Evening]:C(_B)[T.r],-0.277502,4.695550e-119
2,day_time,handiness,61,Beta,924,24,2,2,1.817602e-86,388.430786,1,C(_A)[T.Evening]:C(_B)[T.r],-0.322512,1.817602e-86
3,day_time,handiness,8,Delta,924,24,2,2,2.555466e-66,295.916401,1,C(_A)[T.Evening]:C(_B)[T.r],-1.043237,2.555466e-66
4,day_time,handiness,8,Alpha,924,24,2,2,4.455874e-62,276.451317,1,C(_A)[T.Evening]:C(_B)[T.r],-0.789280,4.455874e-62
5,day_time,handiness,40,Tetta,924,24,2,2,1.842776e-43,191.085137,1,C(_A)[T.Evening]:C(_B)[T.r],-0.439366,1.842776e-43
6,day_time,handiness,8,Beta,924,24,2,2,1.087132e-31,137.205804,1,C(_A)[T.Evening]:C(_B)[T.r],-0.564451,1.087132e-31
7,day_time,handiness,61,Tetta,924,24,2,2,1.601613e-22,95.342212,1,C(_A)[T.Evening]:C(_B)[T.r],-0.323132,1.601613e-22
8,day_time,handiness,40,Alpha,924,24,2,2,2.031457e-20,85.760084,1,C(_A)[T.Evening]:C(_B)[T.r],-0.383044,2.031457e-20
9,day_time,handiness,40,Delta,924,24,2,2,1.771409e-15,63.304037,1,C(_A)[T.Evening]:C(_B)[T.r],-0.470687,1.771409e-15
10,day_time,handiness,12,Tetta,924,24,2,2,2.383221e-14,58.187222,1,C(_A)[T.Evening]:C(_B)[T.r],-0.302433,2.383221e-14
11,day_time,handiness,61,Alpha,924,24,2,2,4.571592e-10,38.852111,1,C(_A)[T.Evening]:C(_B)[T.r],-0.312854,4.571592e-10
12,day_time,handiness,34,Beta,924,24,2,2,7.970525e-07,24.364962,1,C(_A)[T.Evening]:C(_B)[T.r],-0.060053,7.970525e-07
13,day_time,handiness,12,Delta,924,24,2,2,3.955960e-06,21.286069,1,C(_A)[T.Evening]:C(_B)[T.r],-0.361238,3.955960e-06
14,day_time,handiness,12,Alpha,924,24,2,2,4.883573e-05,16.492778,1,C(_A)[T.Evening]:C(_B)[T.r],-0.257123,4.883573e-05

Interaction: age×handiness:   0%|          | 0/252 [00:00<?, ?feat/s]

TOP interaction: age × handiness

,feature_A,feature_B,channel,band,n_obs,n_subjects,levels_A,levels_B,p_interaction_joint,stat_interaction_joint,df_interaction_terms,interaction_term,interaction_coef,interaction_p_single
0,age,handiness,57,Beta,1197,31,3,2,0.966069,0.069040,2,MULTI,NaN,NaN
1,age,handiness,21,Beta,1197,31,3,2,0.976646,0.047263,2,MULTI,NaN,NaN
2,age,handiness,48,Beta,1197,31,3,2,0.977502,0.045510,2,MULTI,NaN,NaN
3,age,handiness,60,Delta,1197,31,3,2,0.978413,0.043647,2,MULTI,NaN,NaN
4,age,handiness,17,Beta,1197,31,3,2,0.979010,0.042427,2,MULTI,NaN,NaN
5,age,handiness,32,Delta,1197,31,3,2,0.979703,0.041013,2,MULTI,NaN,NaN
6,age,handiness,0,Alpha,1197,31,3,2,0.980425,0.039537,2,MULTI,NaN,NaN
7,age,handiness,33,Beta,1197,31,3,2,0.980673,0.039033,2,MULTI,NaN,NaN
8,age,handiness,38,Beta,1197,31,3,2,0.981327,0.037700,2,MULTI,NaN,NaN
9,age,handiness,59,Beta,1197,31,3,2,0.982678,0.034947,2,MULTI,NaN,NaN
10,age,handiness,23,Beta,1197,31,3,2,0.982788,0.034724,2,MULTI,NaN,NaN
11,age,handiness,18,Beta,1197,31,3,2,0.983458,0.033360,2,MULTI,NaN,NaN
12,age,handiness,36,Beta,1197,31,3,2,0.983860,0.032542,2,MULTI,NaN,NaN
13,age,handiness,33,Delta,1197,31,3,2,0.984317,0.031615,2,MULTI,NaN,NaN
14,age,handiness,22,Beta,1197,31,3,2,0.984443,0.031358,2,MULTI,NaN,NaN